Controllers/AdminController.cs
using System;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Net.Mail;
using System.Net;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index(Models.User user)
        {

            return View(user);
        }

        public ActionResult AdminEmail(Models.User user)
        {
            return View(user);
        }

        public ActionResult SendAllUsersEmail(string emailBody, Models.User user)
        {
            string[] email = GetAllUserEmail();
            for (int i = 0; i < GetAllUserEmail().Length; i++)
            {
                using (MailMessage mail = new MailMessage())
                {
                    mail.From = new MailAddress("ito5032email@gmail.com");
                    // put recepitent email here

                    mail.To.Add(email[i]);

                    mail.Subject = "Email from PetsaGram";
                    mail.Body = emailBody;
                    mail.IsBodyHtml = true;
                    mail.Attachments.Add(new Attachment("C:/Users/davch/source/repos/WebApplication4/Image/form.png"));
                    using (SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587))
                    {
                        smtp.Credentials = new NetworkCredential("ito5032email@gmail.com", "namdbcfxkskxusht");
                        smtp.EnableSsl = true;
                        smtp.Send(mail);
                    }
                }
            }
            
            return View("EmailSent", user);
        }

        public string[] GetAllUserEmail()
        {
            string[] email = new string[GetAllUserEmailCount()];
            Connection connectionString = new Connection();
            SqlConnection connection = new SqlConnection(connectionString.GetConnection());
            String query = "SELECT Email FROM Account WHERE UserType = \'User\'";
            using (SqlCommand command = new SqlCommand(query, connection))
            {
                SqlDataReader reader;
                try
                {
                    connection.Open();
                    reader = command.ExecuteReader();
                    int i = 0;
                    while (reader.Read())
                    {
                         email[i] = reader["Email"].ToString();
                        i++;
                    }
                }
                catch
                {
                }
            }

            return email;
        }

        public int GetAllUserEmailCount()
        {
            int count = 0;
            Connection connectionString = new Connection();
            SqlConnection connection = new SqlConnection(connectionString.GetConnection());       
            String query = "SELECT COUNT(Email) FROM Account WHERE UserType = \'User\'";
            using (SqlCommand command = new SqlCommand(query, connection))
            {
                SqlDataReader reader;
                try
                {
                    connection.Open();
                    reader = command.ExecuteReader();

                    if (reader.Read())
                    {
                        count = int.Parse(reader[0].ToString());
                    }
                }
                catch
                {
                }
            }
            return count;
        }

        public ActionResult EmailSent(Models.User user)
        {
            return View(user);
        }

        public ActionResult UserList(Models.User user)
        {
            AccountController account = new AccountController();
            user.UserList = account.GetUserList();
            return View(user);
        }
    }
}

Controllers/PetController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Data.SqlClient;

using WebApplication4.Models;


namespace WebApplication4.Controllers
{
    public class PetController : Controller
    {
        // GET: Pet
        public ActionResult Index(Models.User user)
        {
            return View(user); ;
        }

        public ActionResult AddPets(Models.User user)
        {
            return View(user);
        }
        public ActionResult PetAdd(string petName, string petBreed,string vaccination,
            string year, string month, string day, Models.User user)
        {
            try
            {
                int userId = int.Parse(user.Id.ToString());

                Connection connectionString = new Connection();
                using (SqlConnection connection = new SqlConnection(connectionString.GetConnection()))
                {
                    if (vaccination == "Yes")
                    {
                        DateTime date = SetDates(year, month, day);
                        // protection against SQL injection using @parameter
                        String query = "INSERT INTO Pets (Id,PetName, PetBreed, FirstVaccination, FirstVaccinationDate)" +
                            " VALUES (@Id,@PetName, @PetBreed, @FirstVaccination, @FirstVaccinationDate)";
                        using (SqlCommand command = new SqlCommand(query, connection))
                        {
                            command.Parameters.AddWithValue("@Id", userId);
                            command.Parameters.AddWithValue("@PetName", petName);
                            command.Parameters.AddWithValue("@PetBreed", petBreed);
                            command.Parameters.AddWithValue("@FirstVaccination", vaccination);
                            command.Parameters.AddWithValue("@FirstVaccinationDate", date);
                            connection.Open();
                            int result = command.ExecuteNonQuery();
                            // Check Error
                            if (result < 0)
                                Console.WriteLine("Error inserting data into Database!");
                        }
                    }

                    if (vaccination == "No")
                    {
                        // protection against SQL injection using @parameter
                        String query = "INSERT INTO Pets (Id,PetName, PetBreed) VALUES (@Id,@PetName, @PetBreed)";
                        using (SqlCommand command = new SqlCommand(query, connection))
                        {
                            command.Parameters.AddWithValue("@Id", userId);
                            command.Parameters.AddWithValue("@PetName", petName);
                            command.Parameters.AddWithValue("@PetBreed", petBreed);
                            connection.Open();
                            int result = command.ExecuteNonQuery();
                            // Check Error
                            if (result < 0)
                                Console.WriteLine("Error inserting data into Database!");
                        }
                    }

                }
                return View("PetAdded", user);
            }
            catch
            {
                return View();
            }

        }

        public DateTime SetDates(string year, string month, string day)
        {
            DateTime date = new DateTime();
            if (month == "January")
            {
                month = "01";
            }
            if (month == "February")
            {
                month = "02";
            }
            if (month == "March")
            {
                month = "03";
            }
            if (month == "April")
            {
                month = "04";
            }
            if (month == "May")
            {
                month = "05";
            }
            if (month == "June")
            {
                month = "06";
            }
            if (month == "July")
            {
                month = "07";
            }
            if (month == "August")
            {
                month = "08";
            }
            if (month == "September")
            {
                month = "09";
            }
            if (month == "October")
            {
                month = "10";
            }
            if (month == "November")
            {
                month = "11";
            }
            if (month == "December")
            {
                month = "12";
            }

            date = DateTime.Parse(year + "-" + month + "-" + day);

            return date;
        }
        public ActionResult PetAdded(Models.User user)
        {
            return View("PetAdded", user);
        }

        public ActionResult Vaccination(Models.User user)
        {
            user.PetSelectList = new SelectList("String", "test", "mark");
            return View(user);
        }

        public ActionResult AddVaccination(string year, string month, string day, Models.User user)
        {
            return View(user);
        }

        public ActionResult BarChart(Models.User user)
        {
            // fill pie chart with info
            var pieChartData = GetPieChartData();
            user.PieChartData = pieChartData;
            return View(user);
        }

        // get the data for the pie chart
        private PieChartVM GetPieChartData()
        {
            PieChartVM model = new PieChartVM();
            List<string> labels = new List<string>();
            labels.Add("Pomeranian");
            labels.Add("Bulldog");
            labels.Add("British Shorthair");
            labels.Add("Siamese");
            labels.Add("German Shepherd");
            labels.Add("Golden Retriever");
            labels.Add("Poodle");
            labels.Add("Husky");
            labels.Add("Pug");
            labels.Add("Sphynx");
            labels.Add("Munchkin");
            labels.Add("Chihuahua");
            model.labels = labels;
            List<PieChartChildVM> datasets = new List<PieChartChildVM>();
            PieChartChildVM piechart = new PieChartChildVM();
            List<string> backgroundColorList = new List<string>();
            List<int> dataList = new List<int>();
            foreach (string label in labels)
            {
                if (label == "Pomeranian")
                {
                    backgroundColorList.Add("#cc882e");
                    dataList.Add(GetDataCount("Pomeranian"));
                }
                if (label == "Bulldog")
                {
                    backgroundColorList.Add("#636968");
                    dataList.Add(GetDataCount("Bulldog"));
                }
                if (label == "British Shorthair")
                {
                    backgroundColorList.Add("#e3e1a8");
                    dataList.Add(GetDataCount("British Shorthair"));
                }
                if (label == "Siamese")
                {
                    backgroundColorList.Add("#cca8e3");
                    dataList.Add(GetDataCount("Siamese"));
                }
                if (label == "German Shepherd")
                {
                    backgroundColorList.Add("#4B5320");
                    dataList.Add(GetDataCount("German Shepherd"));
                }
                if (label == "Golden Retriever")
                {
                    backgroundColorList.Add("#583759");
                    dataList.Add(GetDataCount("Golden Retriever"));
                }
                if (label == "Poodle")
                {
                    backgroundColorList.Add("#FF6700");
                    dataList.Add(GetDataCount("Poodle"));
                }
                if (label == "Husky")
                {
                    backgroundColorList.Add("#3D3635");
                    dataList.Add(GetDataCount("Husky"));
                }
                if (label == "Pug")
                {
                    backgroundColorList.Add("#827B60");
                    dataList.Add(GetDataCount("Pug"));
                }
                if (label == "Sphynx")
                {
                    backgroundColorList.Add("#FF3380");
                    dataList.Add(GetDataCount("Sphynx"));
                }
                if (label == "Munchkin")
                {
                    backgroundColorList.Add("#FFFC33");
                    dataList.Add(GetDataCount("Munchkin"));
                }
                if (label == "Chihuahua")
                {
                    backgroundColorList.Add("#FF3333");
                    dataList.Add(GetDataCount("Chihuahua"));
                }
            }
            piechart.backgroundColor = backgroundColorList;
            piechart.data = dataList;
            datasets.Add(piechart);
            model.datasets = datasets;
            return model;
        }

        public int GetDataCount(string breed)
        {
            Connection connectionString = new Connection();
            SqlConnection connection = new SqlConnection(connectionString.GetConnection());
            int number = 0;
            //no need for parameters are declared.
            String query = "SELECT COUNT(PetBreed) FROM Pets WHERE PetBreed = \'"+ breed + "\'";

            using (SqlCommand command = new SqlCommand(query, connection))
            {
                SqlDataReader reader;
                try
                {
                    connection.Open();
                    reader = command.ExecuteReader();

                    if (reader.Read())
                    {
                        number = int.Parse(reader[0].ToString());
                    }
                }
                catch
                {
                }
            }
            return number;
        }

        public ActionResult PieChart(Models.User user)
        {
            // fill pie chart with info

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PetsaGram", "Login", "Account", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Create New Account", "Create", "Account")</li>
                    <li>@Html.ActionLink("Log in", "Login", "Account")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAdmin.cshtml
@model WebApplication4.Models.User
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Admin", Model, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Log Out", "Login", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutUser.cshtml
@model WebApplication4.Models.User
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Home", "Index", "Home", Model, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Pets", "Index", "Pet", Model, null)</li>
                    <li>@Html.ActionLink("Vets", "Index", "Vet", Model, null)</li>
                    <li>@Html.ActionLink("Log Out", "Login", "Account")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>