Controllers/VetController.cs
using System;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Net.Mail;
using System.Net;
using WebApplication4.Models;

namespace WebApplication4.Controllers
{
    public class VetController : Controller
    {
        // GET: Vet
        public ActionResult Index(Models.User user)
        {
            return View(user); ;
        }

        public ActionResult Vet(Models.User user)
        {
            user.RoyaltyVets = VetRating("royaltyvets");
            user.PetVetClub = VetRating("petvetclub");
            user.CareVeterinary = VetRating("careveterinary");
            user.PetVetClinic = VetRating("petvetclinic");

            return View(user);
        }

        public int VetRating(string vet)
        {
            Connection connectionString = new Connection();
            SqlConnection connection = new SqlConnection(connectionString.GetConnection());
            
            int number = 0;
            //no need for parameters are declared.
            String query = "SELECT AVG(VetRating) FROM Vet WHERE VetName = \'"+ vet + "\'";
            using (SqlCommand command = new SqlCommand(query, connection))
            {
                SqlDataReader reader;
                try
                {
                    connection.Open();
                    reader = command.ExecuteReader();

                    if (reader.Read())
                    {
                        number = int.Parse(reader[0].ToString());
                    }
                }
                catch
                {
                }
            }
            return number;
        }

        public ActionResult BookRoyaltyVets(Models.User user)
        {
            return View(user);
        }

        public ActionResult BookRoyaltyVetEmail(string emailBody, Models.User user)
        {

            using (MailMessage mail = new MailMessage())
            {
                mail.From = new MailAddress("ito5032email@gmail.com");
                // put recepitent email here
                mail.To.Add("junenetjourney@gmail.com");
                mail.Subject = "Email For Royalty vets";
                mail.Body = "<h1> '" + emailBody + "'</h1>";
                mail.IsBodyHtml = true;

                using (SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587))
                {
                    smtp.Credentials = new NetworkCredential("ito5032email@gmail.com", "namdbcfxkskxusht");
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                }
            }
            return View("EmailSent", user);
        }

        public ActionResult BookPetVetClub(Models.User user)
        {
            return View(user);
        }

        public ActionResult BookPetVetClubEmail(string emailBody, Models.User user)
        {

            using (MailMessage mail = new MailMessage())
            {
                mail.From = new MailAddress("ito5032email@gmail.com");
                // put recepitent email here
                mail.To.Add("junenetjourney@gmail.com");
                mail.Subject = "Email for Pet Vet Club";
                mail.Body = "<h1> '" + emailBody + "'</h1>";
                mail.IsBodyHtml = true;

                using (SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587))
                {
                    smtp.Credentials = new NetworkCredential("ito5032email@gmail.com", "namdbcfxkskxusht");
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                }
            }
            return View("EmailSent", user);
        }

        public ActionResult BookPetVetClinic(Models.User user)
        {
            return View(user);
        }

        public ActionResult BookPetVetClinicEmail(string emailBody, Models.User user)
        {

            using (MailMessage mail = new MailMessage())
            {
                mail.From = new MailAddress("ito5032email@gmail.com");
                // put recepitent email here
                mail.To.Add("junenetjourney@gmail.com");
                mail.Subject = "Email for Pet Vet Clinic";
                mail.Body = "<h1> '" + emailBody + "'</h1>";
                mail.IsBodyHtml = true;

                using (SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587))
                {
                    smtp.Credentials = new NetworkCredential("ito5032email@gmail.com", "namdbcfxkskxusht");
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                }
            }
            return View("EmailSent", user);
        }

        public ActionResult BookCareVeterinary(Models.User user)
        {
            return View(user);
        }

        public ActionResult BookCareVeterinaryEmail(string emailBody, Models.User user)
        {

            using (MailMessage mail = new MailMessage())
            {
                mail.From = new MailAddress("ito5032email@gmail.com");
                // put recepitent email here
                mail.To.Add("junenetjourney@gmail.com");
                mail.Subject = "Email for Care Veterinary";
                mail.Body = "<h1> '" + emailBody + "'</h1>";
                mail.IsBodyHtml = true;

                using (SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587))
                {
                    smtp.Credentials = new NetworkCredential("ito5032email@gmail.com", "namdbcfxkskxusht");
                    smtp.EnableSsl = true;
                    smtp.Send(mail);
                }
            }
            return View("EmailSent", user);
        }


        public ActionResult RatingDone(Models.User user)
        {
            return View(user);
        }
        
        public ActionResult RateRoyaltyVets(Models.User user)
        {
            return View(user);
        }
        public ActionResult RoyaltyVetsRate(string rating, Models.User user)
        {
            int vetRating = int.Parse(rating);
            Connection connectionString = new Connection();
            using (SqlConnection connection = new SqlConnection(connectionString.GetConnection()))
            {
                String query = "INSERT INTO Vet (VetName,VetRating) VALUES (@VetName,@VetRating)";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@VetName", "royaltyvets");
                    command.Parameters.AddWithValue("@VetRating", vetRating);
                    connection.Open();
                    int result = command.ExecuteNonQuery();
                    // Check Error
                    if (result < 0)
                        Console.WriteLine("Error inserting data into Database!");
                }
            }
            return View("RatingDone",user);
        }

        public ActionResult RateCareVeterinary(Models.User user)
        {
            return View(user);
        }
        public ActionResult CareVeterinaryRate(string rating, Models.User user)
        {
            int vetRating = int.Parse(rating);
            Connection connectionString = new Connection();
            using (SqlConnection connection = new SqlConnection(connectionString.GetConnection()))
            {
                String query = "INSERT INTO Vet (VetName,VetRating) VALUES (@VetName,@VetRating)";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@VetName", "careveterinary");
                    command.Parameters.AddWithValue("@VetRating", vetRating);
                    connection.Open();
                    int result = command.ExecuteNonQuery();
                    // Check Error
                    if (result < 0)
                        Console.WriteLine("Error inserting data into Database!");
                }
            }
            return View("RatingDone", user);
        }

        public ActionResult RatePetVetClinic(Models.User user)
        {
            return View(user);
        }

        public ActionResult PetVetClinicRate(string rating, Models.User user)
        {
            int vetRating = int.Parse(rating);
            Connection connectionString = new Connection();
            using (SqlConnection connection = new SqlConnection(connectionString.GetConnection()))
            {
                String query = "INSERT INTO Vet (VetName,VetRating) VALUES (@VetName,@VetRating)";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@VetName", "petvetclinic");
                    command.Parameters.AddWithValue("@VetRating", vetRating);
                    connection.Open();
                    int result = command.ExecuteNonQuery();
                    // Check Error
                    if (result < 0)
                        Console.WriteLine("Error inserting data into Database!");
                }
            }
            return View("RatingDone", user);
        }

        public ActionResult RatePetVetClub(Models.User user)
        {
            return View(user);
        }

        public ActionResult PetVetClubRate(string rating, Models.User user)
        {
            int vetRating = int.Parse(rating);
            Connection connectionString = new Connection();
            using (SqlConnection connection = new SqlConnection(connectionString.GetConnection()))
            {
                String query = "INSERT INTO Vet (VetName,VetRating) VALUES (@VetName,@VetRating)";
                using (SqlCommand command = new SqlCommand(query, connection))
                {
                    command.Parameters.AddWithValue("@VetName", "petvetclub");
                    command.Parameters.AddWithValue("@VetRating", vetRating);
                    connection.Open();
                    int result = command.ExecuteNonQuery();
                    // Check Error
                    if (result < 0)

Views/Vet/BookCareVeterinary.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "BookCareVeterinary";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Email Care Veterinary</h2>


<html>
<body>
    @using (Html.BeginForm("BookCareVeterinaryEmail", "Vet", Model, FormMethod.Post))
    {
        @Html.TextArea("emailBody", new { @class = "form-control", @rows = 20, @columns = 10 })
        <br />
        @Html.TextBox("button", "Send Email", new { Type = "submit" })
    }
</body>
<hr />
@Html.ActionLink("Back To Home", "Index", "Home", Model, null)
</html>

Views/Vet/BookPetVetClinic.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "BookPetVetClinic";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Email Pet Vet Clinic</h2>


<html>
<body>
    @using (Html.BeginForm("BookPetVetClinicEmail", "Vet", Model, FormMethod.Post))
    {
        @Html.TextArea("emailBody", new { @class = "form-control", @rows = 20, @columns = 10 })
        <br />
        @Html.TextBox("button", "Send Email", new { Type = "submit" })
    }
</body>
<hr />
@Html.ActionLink("Back To Home", "Index", "Home", Model, null)
</html>

Views/Vet/BookPetVetClub.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "BookPetVetClub";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Email Pet Vet Club</h2>


<html>
<body>
    @using (Html.BeginForm("BookPetVetClubEmail", "Vet", Model, FormMethod.Post))
    {
        @Html.TextArea("emailBody", new { @class = "form-control", @rows = 20, @columns = 10 })
        <br />
        @Html.TextBox("button", "Send Email", new { Type = "submit" })
    }
</body>
<hr />
@Html.ActionLink("Back To Home", "Index", "Home", Model, null)
</html>

Views/Vet/BookRoyaltyVets.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "BookRoyaltyVets";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Email Royalty Vets</h2>

<html>
<body>
    @using (Html.BeginForm("BookRoyaltyVetEmail", "Vet", Model, FormMethod.Post))
    {
        @Html.TextArea("emailBody", new { @class = "form-control", @rows = 20, @columns = 10 })
        <br />
        @Html.TextBox("button", "Send Email", new {Type="submit"})
    }
</body>
<hr />
@Html.ActionLink("Back To Home", "Index", "Home", Model, null)
</html>

Views/Vet/EmailSent.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "EmailSent";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
@using (Html.BeginForm("EmailSent", "Home", Model))

{<div>

        <hr />
        <dl class="dl-horizontal">

            <h2>Email Sent</h2>
            <body>
                <br />
                @Html.ActionLink("Back To Vet", "Vet", "Vet", Model, null)
                <br />
            </body>
                <br />



                </div>
           

}</dl>
</div>

Views/Vet/Index.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";

}

<div>

    <hr />
    <dl class="dl-horizontal">

        <h2>Home Page</h2>
        <body>

            <label>User Name : </label>
            @Html.DisplayFor(model => model.UserName)
            <br />
            <label>Email : </label>
            @Html.DisplayFor(model => model.Email)
            <br />
            @Html.ActionLink("View Partnered Vets", "Vet", "Vet", Model, null)
            <br />
        </body>


    </dl>
</div>


    

Views/Vet/RateCareVeterinary.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "RateCareVeterinary";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Rate Care Veterinary</h2>
<html>
<head>
    <title>Page Title</title>
</head>
<body>
    @using (Html.BeginForm("CareVeterinaryRate", "Vet", Model, FormMethod.Post))
    {
        <label>Rate vet 1 to 10</label>
        <br />
        <label>10 being the highest score and 1 being the lowest score</label>
        @Html.DropDownList("rating",
        Enumerable.Range(1, 10).Select(i => new SelectListItem
        { Text = i.ToString(), Value = i.ToString() }),
        new { placeholder = Html.DisplayNameFor(model => model.VetRating), @class = "form-control" })
        <hr />
        @Html.TextBox("button", "Submit Rating", new { Type = "submit" })
    }
</body>
</html>

Views/Vet/RatePetVetClinic.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "RatePetVetClinic";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Rate Pet Vet Clinic</h2>
<html>
<head>
    <title>Page Title</title>
</head>
<body>
    @using (Html.BeginForm("PetVetClinicRate", "Vet", Model, FormMethod.Post))
    {
        <label>Rate vet 1 to 10</label>
        <br />
        <label>10 being the highest score and 1 being the lowest score</label>
        @Html.DropDownList("rating",
        Enumerable.Range(1, 10).Select(i => new SelectListItem
        { Text = i.ToString(), Value = i.ToString() }),
        new { placeholder = Html.DisplayNameFor(model => model.VetRating), @class = "form-control" })
        <hr />
        @Html.TextBox("button", "Submit Rating", new { Type = "submit" })
    }
</body>
</html>

Views/Vet/RatePetVetClub.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "RatePetVetClub";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Rate Pet Vet Club</h2>
<html>
<head>
    <title>Page Title</title>
</head>
<body>
    @using (Html.BeginForm("PetVetClubRate", "Vet", Model, FormMethod.Post))
    {
        <label>Rate vet 1 to 10</label>
        <br />
        <label>10 being the highest score and 1 being the lowest score</label>
        @Html.DropDownList("rating",
        Enumerable.Range(1, 10).Select(i => new SelectListItem
        { Text = i.ToString(), Value = i.ToString() }),
        new { placeholder = Html.DisplayNameFor(model => model.VetRating), @class = "form-control" })
        <hr />
        @Html.TextBox("button", "Submit Rating", new { Type = "submit" })
    }
</body>
</html>

Views/Vet/RateRoyaltyVets.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "RateRoyaltyVets";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Rate Royalty Vets</h2>
<html>
<head>
    <title>Page Title</title>
</head>
<body>
    @using (Html.BeginForm("RoyaltyVetsRate", "Vet", Model, FormMethod.Post))
    {
        <label>Rate vet 1 to 10</label>
        <br />
        <label>10 being the highest score and 1 being the lowest score</label>
        @Html.DropDownList("rating",
        Enumerable.Range(1, 10).Select(i => new SelectListItem
        { Text = i.ToString(), Value = i.ToString() }),
        new { placeholder = Html.DisplayNameFor(model => model.VetRating), @class = "form-control" })
        <hr />
        @Html.TextBox("button", "Submit Rating", new { Type = "submit" })
    }
</body>
</html>

Views/Vet/RatingDone.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "RatingDone";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Rating Done</h2>

@Html.ActionLink("Back to Vet home", "Vet", "Vet", Model, null)

Views/Vet/Vet.cshtml
@model WebApplication4.Models.User

@{
    ViewBag.Title = "Vet";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<html>
<head>
    <title>Page Title</title>
</head>
<body>
    <h1>Royalty Vets</h1>
    <div style="display:inline-block;vertical-align:top;">
        <img src="~/image/royaltyvets.png">
    </div>
    <div style="display:inline-block;">
        <p>
            @Html.ActionLink("Email for Booking with this veterinarian", "BookRoyaltyVets", "Vet", Model, null)
            <br />
            <br />
            Monday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;7am - 6pm
            <br />
            Tuesday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 7am - 6pm
            <br />
            Wednesday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  7am - 6pm
            <br />
            Thursday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 7am - 10pm
            <br />
            Friday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7am - 6pm
            <br />
            Saturday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9am - 7pm
            <br />
            Sunday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  9am - 2pm
            <br />
            <h4>Current Vet Rating</h4>

            @Html.DisplayFor(model => model.RoyaltyVets)
            <br />
            @Html.ActionLink("Rate this veterinarian", "RateRoyaltyVets", "Vet", Model, null)
        </p>
    </div>
    <hr>
    <div></div>
    <h1>Pet Vet Club</h1>
    <div style="display:inline-block;vertical-align:top;">
        <img src="~/image/petvetclub.png">
    </div>
    <div style="display:inline-block;">
        <p>
            @Html.ActionLink("Email for Booking with this veterinarian", "BookPetVetClub", "Vet", Model, null)
            <br />
            <br />
            Monday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;9am - 5pm
            <br />
            Tuesday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 9am - 5pm
            <br />
            Wednesday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  9am - 5pm
            <br />
            Thursday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 9am - 7pm
            <br />
            Friday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9am - 5pm
            <br />
            Saturday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 9am - 5pm
            <br />
            Sunday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  9am - 5pm
            <br />
            <h4>Current Vet Rating</h4>
            @Html.DisplayFor(model => model.PetVetClub)
            <br />
            @Html.ActionLink("Rate this veterinarian", "RatePetVetClub", "Vet", Model, null)
        </p>
    </div>
    <hr>
    <div></div>
    <h1>Care Veterinary</h1>
    <div style="display:inline-block;vertical-align:top;">
        <img src="~/image/carevet.png">
    </div>
    <div style="display:inline-block;">
        <p>
            @Html.ActionLink("Email for Booking with this veterinarian", "BookCareVeterinary", "Vet", Model, null)
            <br />
            <br />
            Monday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;8am - 5pm
            <br />
            Tuesday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 8am - 5pm
            <br />
            Wednesday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  8am - 5pm
            <br />
            Thursday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 8am - 8pm
            <br />
            Friday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 8am - 5pm
            <br />
            Saturday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 10am - 4pm
            <br />
            Sunday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  10am - 4pm
            <br />
            <h4>Current Vet Rating</h4>
            @Html.DisplayFor(model => model.CareVeterinary)
            <br />
            @Html.ActionLink("Rate this veterinarian", "RateCareVeterinary", "Vet", Model, null)
        </p>
    </div>
    <hr>
    <div></div>
    <h1>Pet Vet Clinic</h1>
    <div style="display:inline-block;vertical-align:top;">
        <img src="~/image/petvetclinic.png">
    </div>
    <div style="display:inline-block;">
        <p>
            @Html.ActionLink("Email for Booking with this veterinarian", "BookPetVetClinic", "Vet", Model, null)
            <br />
            <br />
            Monday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;6am - 5pm
            <br />
            Tuesday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 6am - 5pm
            <br />
            Wednesday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  6am - 5pm
            <br />
            Thursday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; 6am - 8pm
            <br />
            Friday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 6am - 5pm
            <br />
            Saturday &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 7am - 4pm
            <br />
            Sunday&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  8am - 4pm
            <br />
            <h4>Current Vet Rating</h4>
            @Html.DisplayFor(model => model.PetVetClinic)
            <br />
            @Html.ActionLink("Rate this veterinarian", "RatePetVetClinic", "Vet", Model, null)
        </p>
    </div>
    <div></div>
    <hr>
    <br />
    @Html.ActionLink("Back to home", "Index", "Home", Model, null)
</body>
</html>